### ISSUE TITLE
Missing mysqli extension

### ISSUE THREAD

**Issue by davidmpaz** [jorge07/alpine-php#34]
Hi,

i discovered this trying to run a Wordpress instance. After adding this:
```
RUN apk add -U php7-mysqli@edge-community
```
to dockerfile everything ran again. So could you please add this extension too?

thanks in advance

**Comment by jorge07** [comment]
Yes, I'll add it as soon as possible.
I'll add it only in the wordpress version as this extension is not generally required. 
https://github.com/jorge07/alpine-php/blob/wordpress/7.1/Dockerfile

**Comment by jorge07** [comment]
Both 7.1 and 7.0 were updated. Will be available as soon as builds ends https://hub.docker.com/r/jorge07/alpine-php/builds/

Remember use `docker pull jorge07/apline-php:7.1-wp` to download latest version
