### ISSUE TITLE
Push new updated versions to hub?

### ISSUE THREAD

**Issue by tonivdv** [jorge07/alpine-php#48]
Hi @jorge07 ,

It would be cool if you could refresh the images on the hub with latest php versions.

Cheers

**Comment by jorge07** [comment]
Sure, I'll try to find some time this week 👍

**Comment by tonivdv** [comment]
Perfect. Not urgent. Thanks.

**Comment by tonivdv** [comment]
@jorge07 You don't forget to do this one of these days :) ?

**Comment by jorge07** [comment]
is coming #49

**Comment by jorge07** [comment]
I'll need to wait for xdebug 7.3 package

**Comment by jorge07** [comment]
Tests passing. Updating images in docker hub.

**Comment by jorge07** [comment]
https://cloud.docker.com/repository/docker/jorge07/alpine-php/timeline
