### ISSUE TITLE
Howto add cgi?

### ISSUE THREAD

**Issue by andig** [jorge07/alpine-php#54]
Please let me start by saying a hearty thank you! The immages with their detailed instructions are a life saver!

My application requires php-cgi, however installing it via apk is not sufficient since running yields an error:

    Error loading shared library libpcre.so.1: No such file or directory (needed by /usr/bin/php-cgi)

Any idea how to fix that in an elegant way that will not rebuild the runtime container all the time?

**Comment by jorge07** [comment]
Can you provide a Dockerfile example so I can test it?

**Comment by andig** [comment]
I've just added a 

    RUN apk --update add ca-certificates \
        && echo "@edge-main http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
        && echo "@edge-community http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
        && echo "@cast https://php.codecasts.rocks/v3.8/php-7.3" >> /etc/apk/repositories \
        && apk add -U \
        # Packages
        php-cgi@cast

and copied `/usr/bin/php-cgi` into the runtime image.

It seems though that (at least according to php-config) the cgi sapi is already supported, so that might not even be necessary?

**Comment by jorge07** [comment]
It came with fpm installed by default so fastcgi it's a direct dependency. Probably already installed. If appears in the PHP config, then it's there :)

**Comment by andig** [comment]
Much appreciated, thank you!
