### ISSUE TITLE
Support ARM platform

### ISSUE THREAD

**Issue by andig** [jorge07/alpine-php#55]
Multi-arch images with support for ARM platform would be great. Seems base alpine is already capable of doing this?

**Comment by jorge07** [comment]
It's in the plan. Also add multi stage builds. I'll try to get this done during next week. Also xdebug 2.70 was released so 7.3 should be bug free

**Comment by andig** [comment]
ping @jorge07 any progress on this one? Would be happy to help, if only by testing.

**Comment by jorge07** [comment]
@andig not yet. I'll try to find some time this weekend ;)

**Comment by andig** [comment]
I‘m stille hugely interested in this but confused how to move this forward. I understand the alpine image aleady supports multiarch. If the package repo does the same we might already be set? What I don‘t get though is how to specify the desired architecture during build in order to bundle them up again inside a docker manifest (if thats the process)?

**Comment by andig** [comment]
Answering myself here. https://stackoverflow.com/questions/51400625/build-and-push-a-multi-arch-docker-image explains how to extract arch-specific tags from base multi arch image. I‘ll see how far that approach would get me.

**Comment by andig** [comment]
Ok. I got the basics right, however the cast repo does unfortunately not contain binaries for other architectures:

```
fetch https://php.codecasts.rocks/v3.8/php-7.3/aarch64/APKINDEX.tar.gz
ERROR: https://php.codecasts.rocks/v3.8/php-7.3: No such file or directory
WARNING: Ignoring APKINDEX.f7859436.tar.gz: No such file or directory
WARNING: The repository tag for world dependency 'php@cast' does not exist
...
```

Any thoughts were to get multi-arch binaries?

**Comment by andig** [comment]
Ping @jorge07 if you have any hint where/how to get packages for target architectures I could take this further.

**Comment by jorge07** [comment]
I think will need to compile.

**Comment by andig** [comment]
I've added an issue upstream at https://github.com/codecasts/php-alpine/issues/79

**Comment by jorge07** [comment]
We no longer depend on codecast so this thing is unlocked.

**Comment by jorge07** [comment]
Initial work is done. Will aggregate the manifests to the pipeline and that should do it

**Comment by m0sviatoslav** [comment]
@jorge07 Hi, do you still working on adding support for ARM? It's been a year since the last comment, and I wonder if it has a chance to be done :)

**Comment by jorge07** [comment]
well it's in master

**Comment by jorge07** [comment]
Feedback appreciated: 
https://hub.docker.com/layers/jorge07/alpine-php/8.1/images/sha256-c42c43d0533af132410837446f55d81670fde91a17ef794915fe6b031f4f72cb?context=repo
