### ISSUE TITLE
docker hub BUILD RULES

### ISSUE THREAD

**Issue by m9rco** [jorge07/alpine-php#56]
hi jorge07

 I am currently studying the way you are to build applications，But when I was in configuration `docker hub` , docker hub always prompt can not find `Dokerfile`

https://github.com/m9rco/alpine

![image](https://user-images.githubusercontent.com/18391791/57318086-15d08e80-712c-11e9-9b30-7f0675a7cba8.png)

**Comment by m9rco** [comment]
I don't know where an error in the configuration, looking forward to your reply

**Comment by m9rco** [comment]
The configuration of the way you is the way I have seen the most perfect!

**Comment by jorge07** [comment]
Nice!

The new Docker Hub UI it's killing me. Quite complex to find the most trivial things

**Comment by m9rco** [comment]
hhhhhh, I find the right solution
