### ISSUE TITLE
Xdebug remote_host is ignored by remote_connect_back

### ISSUE THREAD

**Issue by AdrienFelipe** [jorge07/alpine-php#60]
In your dockerfile you setup the host ip as xdebug _remote_host_:
https://github.com/jorge07/alpine-php/blob/c3f14879245d680596be25513b2d9052e3874663/7.3/Dockerfile.dev#L32

But you leave the _remote_connect_back_ set to 1
https://github.com/jorge07/alpine-php/blob/c3f14879245d680596be25513b2d9052e3874663/7.3/devfs/etc/php7/conf.d/00_xdebug.ini#L9

While as the documentation explains:

> **xdebug.remote_connect_back**
If enabled, the _xdebug.remote_host_ setting is ignored and Xdebug will try to connect to the client that made the HTTP request.

Therefore, souldn't you want the _remote_connect_back_ set to 0?

**Comment by jorge07** [comment]
Hi, sorry for the delay. I'll try to look at this in deep this weekend and back to you with proper information

**Comment by jorge07** [comment]
You're right, that's sorted with the last xdebug configuration

**Comment by jorge07** [comment]
https://github.com/jorge07/alpine-php/blob/master/8.0/devfs/etc/php8/conf.d/00_xdebug.ini

You're right about the configuration BTW
