### ISSUE TITLE
Bump images

### ISSUE THREAD

**Issue by Lutacon** [jorge07/alpine-php#61]
Hello, 

Is it possible to upgrade images with new PHP version? PHP Alpine was updated yesterday. 7.2 and 7.3 branches

Thanks @jorge07 👊

**Comment by jorge07** [comment]
Sure. ASAP

**Comment by jorge07** [comment]
Time to upgrade to 7.4 too. Will be done this week

**Comment by jorge07** [comment]
@Lutacon Kraken Released 
https://github.com/jorge07/alpine-php/releases/tag/20-2-2

**Comment by Lutacon** [comment]
Nice 🚂
