### ISSUE TITLE
Bump php7.4 version

### ISSUE THREAD

**Issue by m-vo** [jorge07/alpine-php#70]
Hi,

could you consider bumping the 7.4 image? It's php version is locked to 7.4.0 and there are quite some packages out there already requiring >=7.4.1. :slightly_smiling_face: 

Seems at least 7.4.3 is available from here https://dl.bintray.com/php-alpine/v3.10/php-7.4/x86_64/

Thanks a lot for your work!

**Comment by cv65kr** [comment]
Hey

if you look at GitHub Actions, we used PHP 7.4.3 but images on docker hub is not updated. So @jorge07 maybe you can use GitHub Actions to auto deploy to docker hub?

```
PHP 7.4.3 (cli) (built: Mar 20 2020 07:14:36) ( NTS )
11
Copyright (c) The PHP Group
12
Zend Engine v3.4.0, Copyright (c) Zend Technologies
13
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
14
PHP 7.4.3 (cli) (built: Mar 20 2020 07:14:36) ( NTS )
15
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
16
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
17
Iyo cabesa
18
256M
```

**Comment by jorge07** [comment]
In my todo list for this week. Quarantine with kids at home makes things way slower than usual

**Comment by jorge07** [comment]
Sorry guys

**Comment by m-vo** [comment]
@jorge07 No need to apologize! Take your time. We're glad you're maintaining this image. :-)

(In the meantime adding something like `apk add --upgrade php` does the trick as well.)

**Comment by jorge07** [comment]
Master since now will be always align with Docker Hub.
https://github.com/jorge07/alpine-php/actions/runs/79292062

Thanks for report this 👍

**Comment by jorge07** [comment]
https://hub.docker.com/repository/docker/jorge07/alpine-php/tags?page=1&ordering=last_updated

Here the changes
